### ISSUE TITLE
Fetching gist through github API fetches gist history

### ISSUE THREAD

**Issue by GoldenBug** [Schneegans/dynamic-badges-action#10]
Currently it looks like when fetching a gist using the github API it also fetches the entire history for that gist.
This can be quite large depending on the gist lifetime.

Unfortunately the only way to fetch ONLY the gist in it's current state is with a GET request.

**Comment by Schneegans** [comment]
Hey there! Sorry but I do not really understand your issue. At what point is a gist fetched? Does something take longer than expected? Where should a GET request be used?

**Comment by GoldenBug** [comment]
Here is an example [LINK](https://github.com/facebook/OpenBIC/runs/5690418295?check_suite_focus=true#logs)
(It's totally possible I'm doing something wrong as well.)

In that job [kickoff nightly / Build-Platforms (yv35-cl)](https://github.com/facebook/OpenBIC/runs/5690418295?check_suite_focus=true#logs) there is a step called `Update Build Badges`,
```
auth: ***
    gistID: 62fb115c[4](https://github.com/facebook/OpenBIC/runs/5690418295?
    filename: yv35-cl.json
    label: Build
    message: PASS
    color: green
```

If you expand that step (it might freeze trying) you can see that the output is printing the entire gist history as well.

I haven't dug into code for this action much, but it seems that at least at some point it's fetching the entire gist history?
At the very least it's being output into a log.

**Comment by Schneegans** [comment]
Thanks for the explanation, now it's more clear! I'll look into this later today.

**Comment by Schneegans** [comment]
It seems, that the response by GitHub to the `POST` request for updating the gist contains all this information. I just published a new release which does not log the response anymore. I think there is no real need for logging it anyways... I guess that this should fix you issue!
