### ISSUE TITLE
[FEATURE] Update gist only if changed

### ISSUE THREAD

**Issue by MishaKav** [Schneegans/dynamic-badges-action#16]
First of all thank you for the action, really useful.
It would be nice if you can add some property like `update-if-changed: true` (default may be `false` to keep backward compatibility).
The action will update the gist only if it doesn't exist or if it changed to reduce the amount of revisions, because usually the coverage of tests don't changes a lot, so in my case all the revisions looks like this:

![image](https://user-images.githubusercontent.com/289035/194327236-62981465-df66-42da-8790-ce72946ed5fb.png)

Thank you

**Comment by Schneegans** [comment]
Your changes have been merged! I'll do some more documentation updates and then I'll release a new version. Thank you once more!
