### ISSUE TITLE
Gist by different user

### ISSUE THREAD

**Issue by simon-k** [Schneegans/dynamic-badges-action#2]
Hi

Is it possible to specify the user of the gist? Let's say the gist is created by another user than the owner of the github repo?

**Comment by simon-k** [comment]
I'm talking about the <user> in

https://gist.githubusercontent.com/<user>/<gist-ID>/raw/test.json

**Comment by Schneegans** [comment]
_Reading_ the gist by another user is obviously possible. So you can create a badge in your README.md based on my gist. Like this ![badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/schneegans/2ab8f1d386f13aaebccbd87dac94068d/raw/hello-world.json):

```markdown
![badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/schneegans/2ab8f1d386f13aaebccbd87dac94068d/raw/hello-world.json)
```
_Writing_ the gist by another user is something I never tried. You would definitely need a personal access token (https://github.com/settings/tokens) by that user to be able to write to her gists. Then it may work! I think the gist ID is unique over all users of GitHub.

**Comment by simon-k** [comment]
I tried it out and it works. 

The repo running the task is on an organization X and the gist belongs to user Y. No problem as long as I created the access token that allows to write to the gist and used the gist id.

**Comment by simon-k** [comment]
The question has been answered and everything is good. Closing this issue.
