### ISSUE TITLE
upgrade for node 16

### ISSUE THREAD

**Issue by brainfoolong** [Schneegans/dynamic-badges-action#20]
Hi!

Since a while, node12 is deprecated in git actions.

    Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: schneegans/dynamic-badges-action

Can you please release a new version that fixes this?

See GitHub blogs about that.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Thank you very much for this action.

**Comment by Schneegans** [comment]
Thanks for the report! I think this only required to change one single line. I'll push a new tag (`v1.6.0`) ASAP.

**Comment by brainfoolong** [comment]
Thanks very much. It works now.
