### ISSUE TITLE
How to use it with secret gists?

### ISSUE THREAD

**Issue by uakram11** [Schneegans/dynamic-badges-action#23]
Hi,

I'm trying to use this with secret gist but I'm facing this issue. 

`Error: Failed to create gist, response status code: 404, status message: Not Found`

I tried it with public gists and it works fine with public ones, so the issue is definitely not with the token. Is there something else that needs to be passed while using it with secret gist?

**Comment by adam-grant-hendry** [comment]
@Schneegans I just started getting this too (and not due to what happend in #15 ).

**Comment by adam-grant-hendry** [comment]
@Schneegans False alarm again. I just needed to update my `SECRET` key.

**Comment by uakram11** [comment]
False alarm, the gist ID's creator was different than the one I created PAT for. Other users cannot update GISTS, so the PAT has to be created for the same user. My bad! Closing this issue.

**Comment by Schneegans** [comment]
Thanks for the update! I was just trying to reproduce this and wondered how this could happen :)
