### ISSUE TITLE
Improve the instructions in READEME file

### ISSUE THREAD

**Issue by 0jdk** [Schneegans/dynamic-badges-action#35]

**Comment by Schneegans** [comment]
I would really appreciate some constructive feedback here. At which points do you think information is missing? I think there is a clear step-by-step guide. Where do you struggle?

**Comment by 0jdk** [comment]
Yes, I appreciate the instructions are quite clear except I thought configuration part instructions could be more elaborated, I couldn't push my branch and raise PR.

Anyway thanks for this amazing actions 🤩

**Comment by Schneegans** [comment]
I think you should either provide a clear list of things you would like to have explained in more detail (which concrete piece of information is missing?) or ideally provide a PR. "could be more elaborated" is way too fuzzy...
