### ISSUE TITLE
Action sometimes not outputting any results

### ISSUE THREAD

**Issue by arifer612** [Schneegans/dynamic-badges-action#5]
# Issue

Dynamic Badges Action sometimes does not create the gist.

# Example
A workflow that I used that gave me this problem was [this](https://github.com/arifer612/pippel/blob/master/.github/workflows/pippel-test-19.0.yml). 

## What I expected to happen
1. Create 5 new gists for each of the Python versions with the message "Testing"
2. Perform tests on each of the Python versions
3. Overwrites the message of the previously create gists either with "Success" or "Fail' depending on the test result

## What actually happened
1. Only 2 new gists were created
2. All the tests were performed
3. Only 1 of the created gists was overwritten. 2 new gists was created. So I am left with 1 gist with the message "Testing" and am missing 1 more gist that I expected

## Workflow outcome
Only the gists that were created showed a response output in the logs. The first image below will be the overall workflow progress. Everything checked out just fine. The subsection to this will show screenshots of the responses to Step 1, where only 2 steps produced a non-nil result.

![2021-06-16-@18-49-21-scrot](https://user-images.githubusercontent.com/46054733/122207149-63f01880-ced4-11eb-8c8f-06df5a85a4d4.png)
_Fig 1. Overall workflow result_

### Result of Job 1 of the workflow
After Job 1, only badges for Python 3.8 and 3.9 were displayed correctly.

#### Action producing no results
![2021-06-16-@18-49-56-scrot](https://user-images.githubusercontent.com/46054733/122207320-94d04d80-ced4-11eb-9fff-9362b33d0527.png)
_FIg 2. No result in logs for Python 2.7_
![2021-06-16-@18-50-27-scrot](https://user-images.githubusercontent.com/46054733/122207323-96017a80-ced4-11eb-8139-9d36e08c3dd0.png)
_Fig 3. No result in logs for Python 3.6_
![2021-06-16-@18-50-42-scrot](https://user-images.githubusercontent.com/46054733/122207324-96017a80-ced4-11eb-99a8-8668e0928def.png)
_Fig 4. No result in logs for Python 3.7_

#### Action producing results
![2021-06-16-@18-51-07-scrot](https://user-images.githubusercontent.com/46054733/122207476-c34e2880-ced4-11eb-9a1b-3798b9c4223b.png)
_Fig 5. Non-nil result in logs for Python 3.8_
![2021-06-16-@18-51-23-scrot](https://user-images.githubusercontent.com/46054733/122207481-c47f5580-ced4-11eb-8b53-efb69bcd3e3f.png)
_Fig 6. Non-nil result in logs for Python 3.9_

#### Result on the README file
![image](https://user-images.githubusercontent.com/46054733/122209015-9dc21e80-ced6-11eb-96a6-9f8e4635ea63.png)
_Fig 7. One gist is still missing and another has not been overwritten with the results of the tests_

## Discussion
I am not sure as to what might be the problem, but if I were to make a guess it would be that these processes might have been too rapidly executed, causing some unexpected hiccups.

## Temporary solution
Only a few gists were not created, so it is possible for me to make use of the general idea to manually write gists for the badges with the corresponding `correct' values.

**Comment by Schneegans** [comment]
Thank you for the report! Before we look deeper into this, three things which come to my mind:
* The action _does not_ create the gist, this has to be done manually beforehand. It just creates the "file" in the gist.
* I think concurrent updates to one gist may fail. You could try to setup one gist for each job!
* If this doesn't help, you could try using `@master` instead of `@v1.0.0` as this will contain #3 which adds printing error messages.

**Edit:** I just released a `v1.1.0` which includes these changes. You can use this as well!

**Comment by arifer612** [comment]
Thank you for replying!

1. I miswrote, it is not the gist that is not being created, it is that sometimes the file within the gist that is not being created by the action.
2. I actually did that before by having 1 job for 1 gist file creation within the whole workflow (that meant that my first job was split into multiple jobs) and it worked without a single failure. The only problem though however, was that I had to write out the jobs explicitly and I could not make use of the matrix feature, which I felt was a shame.
3. I will try using `master` and `v1.1.0` and read the logs and hopefully figure out what might the actual problem is!

**Comment by arifer612** [comment]
With the `master` branch of the action, the failures are much more verbose and I can finally see that the issue really is due to the rapid POST requests sent to the GitHub server.

![image](https://user-images.githubusercontent.com/46054733/122411837-ab030a00-cfb7-11eb-92ed-39fbfad641a2.png)
_Fig 1._ Error 500 for when trying to create files in the gist.

![image](https://user-images.githubusercontent.com/46054733/122412686-5c09a480-cfb8-11eb-8f34-971b3b4edfc3.png)
_Fig 2._ Warning received to wait out for available resources.

When there is a push to the branch, there should be ~120 POST requests to generate a (unique) file in the gist but clearly it is too much and a gate is probably set in place to guard against such `attacks'. This is probably why some workflows are asked to wait for resources to be available before being able to proceed.

I will try a different workflow, where the creation of gist files are more `'paced' and see if there is a positive impact overall.

**Comment by Schneegans** [comment]
I think I will close this. If there's anything which can be improved on the Action's side, please let me know :)

**Comment by arifer612** [comment]
Yep, I tried various things but I doubt there's anything I can suggest to improve it to fix the issue. I'll let you know if I find something out.
