### ISSUE TITLE
Shield.io display domain is blocked

### ISSUE THREAD

**Issue by apomalyn** [Schneegans/dynamic-badges-action#6]
Hi! 👋 
First of all, thank you for this action that has been a very handy actions 😄 

We have an issue with it, everything was working fine but two weeks ago the badge changed for: 

![badge](https://img.shields.io/endpoint?url=https://gist.github.com/clubapplets-server/e51406de3b919a69f396642a2bcb413c/raw/notre_dame_master_badge_coverage.json)

Maybe you have an idea?

Here is the [gist generated](https://gist.github.com/clubapplets-server/e51406de3b919a69f396642a2bcb413c/raw/notre_dame_master_badge_coverage.json)

Thank you once again 😄

**Comment by Schneegans** [comment]
If I just use your gist, it works fine for me: ![badge](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/clubapplets-server/e51406de3b919a69f396642a2bcb413c/raw/notre_dame_master_badge_coverage.json)

Here's the URL I used for the badge: `https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/clubapplets-server/e51406de3b919a69f396642a2bcb413c/raw/notre_dame_master_badge_coverage.json`

Can you confirm this? Maybe it was a temporary issue?

**Comment by apomalyn** [comment]
... aaah sometimes I hate myself 😅 

I used `https://gist.github.com` instead of `https://gist.githubusercontent.com` ... well thank you for your help 😄 

I'm closing this, thank you again

**Comment by Schneegans** [comment]
You're welcome :)
