### ISSUE TITLE
Storing json in wiki ?

### ISSUE THREAD

**Issue by ewjoachim** [Schneegans/dynamic-badges-action#7]
Storing the JSON for shields.io in Gist is really smart, but this requires a few shenanigans.
Do you think it might be possible to store the json in a github wiki file?

### Explanations

You can clone a repo's wiki (`git clone git@github.com:owner/repo.wiki.git`) and push files to it. Files pushed to a wiki are not visible in the repo's UI, but you can fetch them through the URL `https://raw.githubusercontent.com/wiki/:owner/:repo/:file-path`. This seems to work even if wiki is disabled for the project. (usually takes a few minutes for the URL to be updated but for the badges, I'd say it's usually not a problem, shields also does caching anyway)

### Pros

- You don't have to configure a gist. This makes the action much easier to configure
- Also, you don't end up with multiple gists linked to repos around your gist account

### Cons

- You mess with the repo's wiki. Not that much that it might be problematic, I think, but still.
- There's no web UI letting you inspect the json. I don't think it's an important part of the action
- GitHub might change their way of doing. In the future, wiki URLs might become unavailable for repos that have disabled wikis. But it seems to work as of today.

### Unknowns

Will the token provided in GitHub actions be enough to push on the wiki ? We'll have to test that.
It's possible that it still requires a PAT, but no gist. But the scope of the PAT might need to be bigger. Need to test this more.

### Conclusion

If you think this is out of scope for this action, I'll probably try on my own (might be a fork of this action)

**Comment by ewjoachim** [comment]
After a test, we'll need a PAT with `repo` scope for this to work.

Most of what would be done is similar to https://github.com/Decathlon/wiki-page-creator-action

**Comment by Schneegans** [comment]
That's a pretty neat idea. I didn't know that the wiki is accessible even if it's disabled! I think we could include this if we make it optional. So user could fall back to the gist option if GitHub changes this behaviour in the future.

Btw, one issue of this action is that it fails if the gist is updated concurrently by a matrix run. I wonder whether this could be any better if we pushed to the wiki instead? We will have to try it.

Would you volunteer to try this approach and create a pull request if it works? That would be awesome!

**Comment by ewjoachim** [comment]
I can try but I can't promise anything. If you don't hear from me by 2 weeks, assume I gave up and it's up for grabs

**Comment by Schneegans** [comment]
I guess I can close this for now :)
